<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <IsPackable>false</IsPackable>
    <RootNamespace>Escola.Testes.Integracao</RootNamespace>
    <AssemblyName>Escola.Testes.Integracao</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\infra\sql\init.sql" Link="init.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="Microsoft.Owin.Testing" Version="4.2.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Escola.Api\Escola.Api.csproj" />
  </ItemGroup>
  <Target Name="CopyXmlDocumentation" AfterTargets="Build">
    <PropertyGroup>
      <ApiXml>$(MSBuildThisFileDirectory)..\..\src\Escola.Api\bin\Escola.Api.xml</ApiXml>
      <AplicacaoXml>$(MSBuildThisFileDirectory)..\..\src\Escola.Aplicacao\bin\$(Configuration)\net48\Escola.Aplicacao.xml</AplicacaoXml>
    </PropertyGroup>
    <Copy SourceFiles="$(ApiXml)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" Condition="Exists('$(ApiXml)')" />
    <Copy SourceFiles="$(AplicacaoXml)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" Condition="Exists('$(AplicacaoXml)')" />
  </Target>
</Project>
