<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>Escola.Aplicacao</RootNamespace>
    <AssemblyName>Escola.Aplicacao</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" Version="6.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Escola.Dominio\Escola.Dominio.csproj" />
  </ItemGroup>
</Project>
